// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// vSB
double vSB(arma::vec x, double p);
RcppExport SEXP _forecastES3_vSB(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(vSB(x, p));
    return rcpp_result_gen;
END_RCPP
}
// vSB_mat
arma::vec vSB_mat(arma::mat x, double p);
RcppExport SEXP _forecastES3_vSB_mat(SEXP xSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(vSB_mat(x, p));
    return rcpp_result_gen;
END_RCPP
}
// vHACC
double vHACC(arma::vec v, int k);
RcppExport SEXP _forecastES3_vHACC(SEXP vSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(vHACC(v, k));
    return rcpp_result_gen;
END_RCPP
}
// t_testC
double t_testC(arma::vec x, int k, double eps);
RcppExport SEXP _forecastES3_t_testC(SEXP xSEXP, SEXP kSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(t_testC(x, k, eps));
    return rcpp_result_gen;
END_RCPP
}
// t_matC
arma::vec t_matC(arma::mat x, int k, double eps);
RcppExport SEXP _forecastES3_t_matC(SEXP xSEXP, SEXP kSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(t_matC(x, k, eps));
    return rcpp_result_gen;
END_RCPP
}
// vHACC_mat
arma::vec vHACC_mat(arma::mat x, int k);
RcppExport SEXP _forecastES3_vHACC_mat(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(vHACC_mat(x, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_forecastES3_vSB", (DL_FUNC) &_forecastES3_vSB, 2},
    {"_forecastES3_vSB_mat", (DL_FUNC) &_forecastES3_vSB_mat, 2},
    {"_forecastES3_vHACC", (DL_FUNC) &_forecastES3_vHACC, 2},
    {"_forecastES3_t_testC", (DL_FUNC) &_forecastES3_t_testC, 3},
    {"_forecastES3_t_matC", (DL_FUNC) &_forecastES3_t_matC, 3},
    {"_forecastES3_vHACC_mat", (DL_FUNC) &_forecastES3_vHACC_mat, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_forecastES3(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
