# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vSB <- function(x, p) {
    .Call('_forecastES3_vSB', PACKAGE = 'forecastES3', x, p)
}

vSB_mat <- function(x, p) {
    .Call('_forecastES3_vSB_mat', PACKAGE = 'forecastES3', x, p)
}

vHACC <- function(v, k) {
    .Call('_forecastES3_vHACC', PACKAGE = 'forecastES3', v, k)
}

t_testC <- function(x, k, eps) {
    .Call('_forecastES3_t_testC', PACKAGE = 'forecastES3', x, k, eps)
}

t_matC <- function(x, k, eps) {
    .Call('_forecastES3_t_matC', PACKAGE = 'forecastES3', x, k, eps)
}

vHACC_mat <- function(x, k) {
    .Call('_forecastES3_vHACC_mat', PACKAGE = 'forecastES3', x, k)
}

